crud food is working
mrtauern/Food_log pull request #4
Opened 2021-11-09 14:22 UTC by hasandk

2021-11-09 14:36 UTC, mrtauern commented on src/main/java/com/base/site/controllers/FoodController.java
> +            model.addAttribute("food", food);
TIP: You can also write it like this
`Food food = model.addAttribute("food", food);`
Then we save some line of code.

2021-11-09 14:54 UTC, mrtauern requested changes
It looks very good, but there are some minor issues that have to be fixed 😉

2021-11-09 14:54 UTC, mrtauern commented on src/main/java/com/base/site/repositories/FoodRepo.java
> +public interface FoodRepo extends JpaRepository<Food, Integer> {
We use Long and not int or integer in our project for DB ID's

2021-11-09 14:54 UTC, mrtauern commented on src/main/java/com/base/site/models/Food.java
> +    private int id;
We use Long and not int or integer in our project for DB ID's

2021-11-09 14:54 UTC, mrtauern commented on src/main/java/com/base/site/security/FoodService.java
> +    void deleteFoodById(int id);
Use findAll(), findById(), save(), deledeById(), and delete() so we have one standard across our project.

2021-11-09 14:54 UTC, mrtauern commented on src/main/resources/templates/createFood.html
> +</head>
Replace this with this:
`<head th:include="fragments/head :: styles"></head>`

2021-11-09 14:54 UTC, mrtauern commented on src/main/resources/templates/fragments/navbar_top.html
> +                <li><a href="/index">Home</a></li>
We have to find a standard to how we do this

2021-11-09 14:54 UTC, mrtauern commented on src/main/java/com/base/site/controllers/FoodController.java
> +    }
Is this used for both create and update food?

2021-11-09 14:54 UTC, mrtauern commented on src/main/java/com/base/site/controllers/FoodController.java
> +    @GetMapping("/showUpdateFood/{id}")
Can we just call it updateFood 😉

2021-11-09 19:48 UTC, niklasld commented on src/main/java/com/base/site/models/Food.java
> +    public void setCarbohydrates(int carbohydrates) {
Database carbohydrates, fat and protein have all been changed to doubles

2021-11-09 19:52 UTC, niklasld commented on src/main/java/com/base/site/models/Food.java
> +    private int fat;
Database carbohydrates, fat and protein have all been changed to doubles

2021-11-10 08:06 UTC, mrtauern commented on src/main/resources/templates/fragments/navbar_top.html
> +                <li><a href="/index">Home</a></li>
Is the link to our home page "/index"?

2021-11-10 09:36 UTC, mrtauern approved these changes
It looks fine

2021-11-10 09:36 UTC, merged