Add Recipe to Dailylog and calculate Calories work
mrtauern/Food_log pull request #88
Opened 2021-12-13 11:46 UTC by hasandk

2021-12-13 12:23 UTC, niklasld requested changes
unit tests fails

2021-12-13 12:57 UTC, niklasld requested changes
recipe should be under food and be able to choose time of day.
you should be able to add, edit and delete from dailylog
you should be able to choose amount

2021-12-14 22:46 UTC, mrtauern commented
I think it's overall looks fine, but I think it's a good idea Niklas also takes at look at it, because it has worked mostly with calorie count etc.

2021-12-15 10:05 UTC, niklasld approved these changes

2021-12-15 10:06 UTC, merged